principal_biblioteca_comentario:
    resource: "@PrincipalBibliotecaBundle/Controller/ComentarioController.php"
    type:     annotation

principal_biblioteca_categorium:
    resource: "@PrincipalBibliotecaBundle/Controller/CategoriumController.php"
    type:     annotation

principal_biblioteca_libro:
    resource: "@PrincipalBibliotecaBundle/Controller/LibroController.php"
    type:     annotation

principal_biblioteca_autor:
    resource: "@PrincipalBibliotecaBundle/Controller/AutorController.php"
    type:     annotation

principal_biblioteca:
    resource: "@PrincipalBibliotecaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin    
