<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-03-27 17:17:00.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Principal\BibliotecaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Principal\BibliotecaBundle\Entity\Autor
 *
 * @ORM\Entity(repositoryClass="Principal\BibliotecaBundle\Entity\AutorRepository"))
 * @Vich\Uploadable
 * @ORM\Table(name="Autor", indexes={@ORM\Index(name="fk_Autor_Usuario1_idx", columns={"usuario_id"})})
 */
class Autor
{
    /**
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $Nombre;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $FotoName;


    /**
     * @ORM\Column(type="string", length=45)
     */
    protected $Nacionalidad;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $Aprobado;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="autor", fileNameProperty="FotoName")
     * 
     * @var File
     */
    protected $Foto;

    /**
     * @ORM\Column(type="integer")
     */
    protected $Usuario_id;

    /**
     * @ORM\ManyToMany(targetEntity="Libro", mappedBy="autor")
     */
    protected $libros;

    /**
     * @ORM\ManyToOne(targetEntity="Usuario", inversedBy="autors")
     * @ORM\JoinColumn(name="usuario_id", referencedColumnName="id")
     */
    protected $usuario;

    public function __construct()
    {
        $this->libros = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Principal\BibliotecaBundle\Entity\Autor
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Nombre.
     *
     * @param string $Nombre
     * @return \Principal\BibliotecaBundle\Entity\Autor
     */
    public function setNombre($Nombre)
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * Get the value of Nombre.
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->Nombre;
    }

    /**
     * Set the value of Nacionalidad.
     *
     * @param string $Nacionalidad
     * @return \Principal\BibliotecaBundle\Entity\Autor
     */
    public function setNacionalidad($Nacionalidad)
    {
        $this->Nacionalidad = $Nacionalidad;

        return $this;
    }

    /**
     * Get the value of Nacionalidad.
     *
     * @return string
     */
    public function getNacionalidad()
    {
        return $this->Nacionalidad;
    }

    /**
     * Set the value of Aprobado.
     *
     * @param boolean $Aprobado
     * @return \Principal\BibliotecaBundle\Entity\Autor
     */
    public function setAprobado($Aprobado)
    {
        $this->Aprobado = $Aprobado;

        return $this;
    }

    /**
     * Get the value of Aprobado.
     *
     * @return boolean
     */
    public function getAprobado()
    {
        return $this->Aprobado;
    }

    /**
     * Set the value of Foto.
     *
     * @param string $Foto
     * @return \Principal\BibliotecaBundle\Entity\Autor
     */
    public function setFoto(File $Foto = null)
    {
        $this->Foto = $Foto;

        return $this;
    }
    
    /**
     * Get the value of Foto.
     *
     * @return string
     */
    public function getFoto()
    {
        return $this->Foto;
    }


    /**
     * Get the value of Foto.
     *
     * @return string
     */
    public function getFotoName()
    {
        return $this->FotoName;
    }

    /**
     * Set the value of FotoName.
     *
     * @return string
     */
    public function setFotoName($name)
    {
        $this->FotoName = $name;
        return $this;
    }


    /**
     * Set the value of Usuario_id.
     *
     * @param integer $Usuario_id
     * @return \Principal\BibliotecaBundle\Entity\Autor
     */
    public function setUsuarioId($Usuario_id)
    {
        $this->Usuario_id = $Usuario_id;

        return $this;
    }

    /**
     * Get the value of Usuario_id.
     *
     * @return integer
     */
    public function getUsuarioId()
    {
        return $this->Usuario_id;
    }

    /**
     * Add Libro entity to collection (one to many).
     *
     * @param \Principal\BibliotecaBundle\Entity\Libro $libro
     * @return \Principal\BibliotecaBundle\Entity\Autor
     */
    public function addLibro(LibroAutor $libro)
    {
        $libro->setAutor($this);
        $this->libros[] = $libro;

        return $this;
    }

    /**
     * Remove Libro entity from collection (one to many).
     *
     * @param \Principal\BibliotecaBundle\Entity\Libro $libro
     * @return \Principal\BibliotecaBundle\Entity\Autor
     */
    public function removeLibro(Libro $libro)
    {
        $this->libros->removeElement($libro);

        return $this;
    }

    /**
     * Get Libro entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getLibros()
    {
        return $this->libros;
    }

    /**
     * Set Usuario entity (many to one).
     *
     * @param \Principal\BibliotecaBundle\Entity\Usuario $usuario
     * @return \Principal\BibliotecaBundle\Entity\Autor
     */
    public function setUsuario(Usuario $usuario = null)
    {
        $this->usuario = $usuario;

        return $this;
    }

    /**
     * Get Usuario entity (many to one).
     *
     * @return \Principal\BibliotecaBundle\Entity\Usuario
     */
    public function getUsuario()
    {
        return $this->usuario;
    }

    public function __sleep()
    {
        return array('id', 'Nombre', 'Nacionalidad', 'Aprobado', 'Foto', 'Usuario_id');
    }

    public function __toString()
    {
        return $this->Nombre;
    }
}
