<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.6-dev (doctrine2-annotation) on 2017-03-29 20:14:52.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Principal\BibliotecaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Principal\BibliotecaBundle\Entity\Licencium
 *
 * @ORM\Entity()
 * @ORM\Table(name="Licencia")
 */
class Licencium
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=250, nullable=true)
     */
    protected $Licencia;

    /**
     * @ORM\Column(name="`Alias`", type="string", length=45, nullable=true)
     */
    protected $Alias;

    /**
     * @ORM\OneToMany(targetEntity="Libro", mappedBy="licencium")
     * @ORM\JoinColumn(name="id", referencedColumnName="Licencia_id")
     */
    protected $libros;

    public function __construct()
    {
        $this->libros = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Principal\BibliotecaBundle\Entity\Licencium
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of Licencia.
     *
     * @param string $Licencia
     * @return \Principal\BibliotecaBundle\Entity\Licencium
     */
    public function setLicencia($Licencia)
    {
        $this->Licencia = $Licencia;

        return $this;
    }

    /**
     * Get the value of Licencia.
     *
     * @return string
     */
    public function getLicencia()
    {
        return $this->Licencia;
    }

    /**
     * Set the value of Alias.
     *
     * @param string $Alias
     * @return \Principal\BibliotecaBundle\Entity\Licencium
     */
    public function setAlias($Alias)
    {
        $this->Alias = $Alias;

        return $this;
    }

    /**
     * Get the value of Alias.
     *
     * @return string
     */
    public function getAlias()
    {
        return $this->Alias;
    }

    /**
     * Add Libro entity to collection (one to many).
     *
     * @param \Principal\BibliotecaBundle\Entity\Libro $libro
     * @return \Principal\BibliotecaBundle\Entity\Licencium
     */
    public function addLibro(Libro $libro)
    {
        $this->libros[] = $libro;

        return $this;
    }

    /**
     * Remove Libro entity from collection (one to many).
     *
     * @param \Principal\BibliotecaBundle\Entity\Libro $libro
     * @return \Principal\BibliotecaBundle\Entity\Licencium
     */
    public function removeLibro(Libro $libro)
    {
        $this->libros->removeElement($libro);

        return $this;
    }

    /**
     * Get Libro entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getLibros()
    {
        return $this->libros;
    }

    public function __sleep()
    {
        return array('id', 'Licencia', 'Alias');
    }

    public function __toString()
    {
        return $this->Licencia;
    }
}
